---
# tasks file for ngnix
- name: install epel-release
  yum:
    name: epel-release
    state: latest
- name: install nginx
  yum:
    name: nginx
    state: latest
    
- name: ensure nginx is started
  service: name=nginx state=started enabled=yes

- name: configure nginx site
  template: src=templates/nginx.conf.j2 dest=/etc/nginx/conf.d/demo mode=0644
  notify: restart nginx

