---
- hosts: webserver 
  tasks:
    - name: install http and other web components  
      yum: 
        name={{item}} state=latest
      with_items: 
        - epel-release
        - httpd
        - mod_wsgi 
        - python-pip
        - python-virtualenv
    
    - name: making sure service httpd is up and running 
      service: name=httpd state=started enabled=yes 

    - name: ensure mod_wsgi is enabled 
      apache2_module: state=present name=wsgi
      notify: httpd restart
 
    - name: copy demo app to the destination web servers
      copy: src=app/ dest=/var/www/demo mode=0755
      notify: httpd restart
    
    - name: copy demo.conf on destination web servers 
      copy: src=demo.conf dest=/etc/httpd/conf.d/ mode=0755
      notify: httpd restart 

    - name: setup python virtual environment 
      pip: requirements=/var/www/demo/requirements.txt virtualenv=/var/www/demo/.venv
      notify: httpd restart

    #- name: 

  handlers: 
    - name: httpd restart 
      service: name=httpd state=restarted 
