---
# tasks file for mysql
- name: install require packages for db server
  yum: name={{item}} state=present update_cache=yes
  with_items:
    - MySQL-python
    - tree
    - fish

- name: Installs EPEL release
  yum: name=epel-release state=latest

- name: installing mysql repo
  yum: name=http://repo.mysql.com/mysql-community-release-el7-5.noarch.rpm state=present

- name: Install my-sql server
  yum: name=mysql-server state=latest update_cache=yes

- name: making sure mysql is running
  service: name=mysql state=started enabled=yes

- name: create demo database
  mysql_db: name= {{db_name}} state=present

- name: create mysql user
  mysql_user: name={{ db_user_name }} password={{ db_user_pass }} priv=demo.*:ALL 
              host='{{db_user_host}}' state=present
