---
# tasks file for httpd
- name: install http and other web components
  yum: name={{item}} state=latest update_cache=yes
  with_items:
    - epel-release
    - httpd
    - mod_wsgi

- name: inserting block on configuration file 
  blockinfile: 
    path: /etc/httpd/conf/httpd.conf 
    block: |
      IncludeOptional conf.d/*.conf
  notify: httpd restart 

- name: making sure service httpd is up and running
  service: name=httpd state=started enabled=yes

- name: ensure mod_wsgi is enabled
  apache2_module: state=present name=wsgi
  notify: httpd restart

