---

- hosts: loadbalancer
  tasks:
    - name: taking down loadbalancing service 
      service: name=nginx state=stopped 
    - wait_for: port=80 state=drained

- hosts: webserver 
  tasks: 
    - name: taking down http service 
      service: name=httpd state=stopped 
    - name: checking if port 80 is completely drained or stopped
      wait_for: port=80 state=drained

- hosts: database
  tasks: 
    - name: Restarting down database service 
      service: name=mysql state=restarted 
    - wait_for: port=3306 state=started

- hosts: webserver
  tasks: 
    - name: Bringing up httpd service 
      service: name=httpd state=started 

- hosts: loadbalancer
  tasks: 
    - name: Bringing up nginx service 
      service: name=nginx state=started    
